Fix bug in comparing function objects detected by Sjoerd:
SystemError: bad argument to internal function

caused by comparing NULL pointer default args.


git-svn-id: http://svn.python.org/projects/python/trunk@8422 6015fed2-1504-0410-9fe1-9d1591cc4771